[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true
  gzip = true
  brotli = true

[build.processing.css]
  minify = true
  gzip = true
  brotli = true

[build.processing.js]
  minify = true
  gzip = true
  brotli = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; font-src 'self' data:"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[redirects]]
  from = "/@:handle/story/:slug"
  to = "/authors/:handle/articles/:slug/"
  status = 301

[[redirects]]
  from = "/@:handle"
  to = "/authors/:handle/"
  status = 301

[[redirects]]
  from = "/topic/:topic"
  to = "/topics/:topic/"
  status = 301
